export JAVA_HOME=/usr/lib/jvm/java-7-oracle/

export HADOOP_PREFIX=/opt/hadoop
export HADOOP_COMMON_HOME=$HADOOP_PREFIX
export HADOOP_HDFS_HOME=$HADOOP_PREFIX
export HADOOP_YARN_HOME=$HADOOP_PREFIX
export HADOOP_MAPRED_HOME=$HADOOP_PREFIX
export HADOOP_HOME=$HADOOP_PREFIX

export HADOOP_STREAMING=$HADOOP_HOME/share/hadoop/tools/lib/hadoop-streaming-2.6.0.jar

export YARN_CONF_DIR=$HADOOP_YARN_HOME/etc/hadoop
export HADOOP_CONF_DIR=$YARN_CONF_DIR

export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_PREFIX/lib/native
export HADOOP_OPTS="-Djava.library.path=$HADOOP_PREFIX/lib -Djava.net.preferIPv4Stack=true"


export HIVE_HOME=/opt/hive

export SPARK_HOME=/opt/spark

export PIG_HOME=/opt/pig

export PATH=$PATH:$PIG_HOME/bin:$SPARK_HOME/bin:$HADOOP_PREFIX/bin:$HADOOP_PREFIX/sbin:$HIVE_HOME/bin

alias hfs="hadoop fs"
alias hls="hfs -ls"

